version: 0.2

phases:
  install:
    runtime-versions:
        java: corretto17
      
  build:
    commands:
      - echo build started on 'date'
      - mvn clean install

artifacts: 
  files:
    - target/java-tomcat-maven-example.war
    - appspec.yml
    - beforeinstall.sh
    - afterinstall.sh
    - applicationstart.sh
    - applicationstop.sh
